### ISSUE TITLE
عدم ذخیره تنظیمات

### ISSUE THREAD

**Issue by paulvek** [NIKJOO/WarpOnWarp-Windows-Client#2]
سلام اول تشکر میکنم از اپ مفیدتون و بعد یک گزارش خواستم بدم نمیدونم داخل ویندوز های دیگه هم همینطوره یا نه در 11 تست گرفتم
وقتی نرم افزارو اجرا میکنیم و یکی از گزینه ها رو انتخاب میکنیم و کانکت میزنیم این به طور کلی این تنظیمات ذخیره نمیشه
یعنی دفعه بعدی که نرم افزارو اجرا کردیم باید دوباره همون گزینه فعال کنیم... اگه یک دیتابیس داشته باشه یا روش دیگری برای ذخیره مثلا در حافظه موقت ویندوز و... درنظر گرفته بشه خوبه تا تنظیمات کاربر ذخیره بشه و برای اجرای دفعات بعدی نیاز نباشه که دوباره  همون ها انتخاب بشن
البته اونقدر مهم نیست و وقتی نمیگیره فعال کردن یک گزینه اما ذخیره بشه بهتره
یک سوال و نگرانی امنیتی هم برام بوجود اومد این لاگ هایی که توی نرم افزار میندازه توسط مدیر سرور یا کسی که اون رو ساخته (یا هر گونه شخص ثالث) قابل ردگیری و مشاهدست؟
چون هر سایت و صفحه ای که باز میشه با تاریخ و زمان و آدرس دقیق ثبت میشه
این لاگ برای چیه و چه کاربردی داره؟ فقط برای اینه که خود کاربر اون رو ببینه؟ در این صورت چه نیازی بهش داره؟ یا اگه نیست چه این در نرم افزار نشان داده میشه چه نمیشد اما لاگ انداخته میشد کاربرد و استفاده ازش چیه؟ ببخشید سوالات برای اینه که خیالمون از امنیت راحت باشه

**Comment by NIKJOO** [comment]
سلام ، نظر لطف شماست
نسخه جدید 0.2 رو امتحان بفرمائید
از IPv4 برای اتصال در اپراتور همراه اول استفاده میشه و از IPv6 برای ایرانسل
لاگ ها توسط خود ابزار Warp.exe ساخته میشن و اگر تحت کنسول هم اجرا کنید همین لاگ ها رو خواهید دید ، برای اینکه کسی دچار سوء تعبیر نشه هر چه در برنامه نمایش داده میشه در برنامه گنجانده شده.

**Comment by paulvek** [comment]
> سلام ، نظر لطف شماست نسخه جدید 0.2 رو امتحان بفرمائید از IPv4 برای اتصال در اپراتور همراه اول استفاده میشه و از IPv6 برای ایرانسل لاگ ها توسط خود ابزار Warp.exe ساخته میشن و اگر تحت کنسول هم اجرا کنید همین لاگ ها رو خواهید دید ، برای اینکه کسی دچار سوء تعبیر نشه هر چه در برنامه نمایش داده میشه در برنامه گنجانده شده.

متشکرم. بله ذخیره گزینه وارپ رو امتحان کردم انجام شد البته یک فایل Setting.INI کنارش ایجاد کردید که از طریق اون هم میتونیم تنظیمات دلخواه رو با TRUE و FALSE انجام بدیم.
فقط تیک سیستم پراکسی جزو موارد نبود و قابلیت ذخیره شدن نداره که اون هم مهم نیست. در کل کارتون خیلی ارزشمنده و همه چیزو عالی درست کردید و با سرعت خوب کار میکنه.
برای همراه اول باید فقط تیک ipv4 فعلا باشه یا گزینه warp on warp و ipv4 با هم؟ اگه میشه لطفا درمورد گزینه psiphon هم توضیح بدید...

**Comment by NIKJOO** [comment]
ممنونم از لطف شما ، سایفون زیاد چیز مهمی نیست ، هم پایدار نیست هم اینکه فقط زمانی کاربرد داره که آی پی کشور خاصی نیاز دارید
شاید به کل حذفش کنم
برای همراه اول باید تیک ipv4 فعال باشه بعدش تست کنید اگر متصل بشه ، میتونید وارپ آن وارپ رو هم فعال کنید.
