### ISSUE TITLE
add support tun mode

### ISSUE THREAD

**Issue by Morrigan-Ship** [NIKJOO/WarpOnWarp-Windows-Client#3]
you can add support tun mode via `tun2socks` repo:
https://github.com/xjasonlyu/tun2socks

or you can use `tun2proxy`:
https://github.com/tun2proxy/tun2proxy

or you can tun mode via singbox:
make a socks outbound in config.json of singbox
enable tun mode via singbox
read singbox documents

please support all these 3 tun mode spped of them are different

**Comment by NIKJOO** [comment]
Sure, the features you want will be added to the program as soon as possible
But adding Tun mode ( like as VPN or enabling tun adapter ) may cause vulnerability issues

**Comment by Morrigan-Ship** [comment]
> may cause vulnerability issues

you can add Experimental tag to this feature
So the user can choose or not

**Comment by Morrigan-Ship** [comment]
مثل هیدیفای که برخی قابلیت هاش رو لیبل یا تگ ازمایشی زده و جلوش نوشته ازمایشی

**Comment by NIKJOO** [comment]
i wrote this app for myself so maybe i add those features in my free times :)
Thanks for advices
