### ISSUE TITLE
Detected: Behavior:Win32/Impact.A!ml on Windows 11

### ISSUE THREAD

**Issue by paulvek** [NIKJOO/WarpOnWarp-Windows-Client#7]
Today i received this and quietened by windows 11 security defender software

**Detected:** Behavior:Win32/Impact.A!ml
Details: **This program is dangerous and executes commands from an attacker.**

![attack](https://github.com/NIKJOO/WarpOnWarp-Windows-Client/assets/153482922/fab4a3b3-e1c0-4fcb-8fd5-8ea569879b6e)

**Comment by Msadr471** [comment]
دقیقا همین الان هم برای من ویندوز برنامه رو به عناون نا ایمن شناسایی کرد.

**Comment by NIKJOO** [comment]
بررسی میکنم ، مشکل رو حل میکنم ، نگران نباشید

**Comment by NIKJOO** [comment]
فکر کنم مشکل حل شد
https://github.com/NIKJOO/WarpOnWarp-Windows-Client/releases/tag/0.2.2

**Comment by paulvek** [comment]
بله درست شد

**Comment by paulvek** [comment]
> فکر کنم مشکل حل شد https://github.com/NIKJOO/WarpOnWarp-Windows-Client/releases/tag/0.2.2

بله درست شد
