### ISSUE TITLE
ویندوز۷

### ISSUE THREAD

**Issue by emisemok** [NIKJOO/WarpOnWarp-Windows-Client#8]
مهندس خداقوت
روی ویندوز۷ اون قسمت لاگ ثابت نمیمونه و فشار زیادی ب رم و سی پیو میاره قائدتا طبیعی نیست
ممنون میشم در مورد ویندوز۷ هم مورد بررسی قرار بدید
با تشکر از زحماتتون🙏

**Comment by NIKJOO** [comment]
سلام و عرض ادب
متاسفانه امکان تست روی ویندوز 7 رو ندارم ، روی VM هم احتمالا" نتیجه واقعی نتونم بگیرم ، فرصت بدید تست کنم ، اگر بتونید اسکرین شات از میزان مصرف بذارید قطعا" کمک کننده خواهد بود که ببینم برنامه اصلی فشار وارد میکنه یا هسته خود وارپ

تشکر
